In [1]:
from nba_api.stats.endpoints import WNBAPlayerGameLogs

logs = WNBAPlayerGameLogs(season_nullable='2024')
df = logs.get_data_frames()[0]

print(df.shape)           # (rows, columns) — how much data came back
print(df.columns.tolist())  # all the column names

ImportError: cannot import name 'WNBAPlayerGameLogs' from 'nba_api.stats.endpoints' (unknown location)

In [2]:
import nba_api.stats.endpoints as ep
wnba_endpoints = [x for x in dir(ep) if 'wnba' in x.lower()]
print(wnba_endpoints)

[]

In [3]:
from nba_api.stats.endpoints import LeagueGameLog

logs = LeagueGameLog(season='2024', league_id='10')
df = logs.get_data_frames()[0]

print(df.shape)
print(df.columns.tolist())

ImportError: cannot import name 'LeagueGameLog' from 'nba_api.stats.endpoints' (unknown location)

In [4]:
import nba_api.stats.endpoints as ep
all_endpoints = [x for x in dir(ep) if not x.startswith('_')]
print(all_endpoints)

[]

In [1]:
from nba_api.stats.endpoints import LeagueGameLog

logs = LeagueGameLog(season='2024', league_id='10')
df = logs.get_data_frames()[0]

print(df.shape)
print(df.columns.tolist())

Exception: Import Missing - Failed to import DataFrame from pandas.

In [1]:
from nba_api.stats.endpoints import LeagueGameLog

logs = LeagueGameLog(season='2024', league_id='10')
df = logs.get_data_frames()[0]

print(df.shape)
print(df.columns.tolist())

AttributeError: module 'numpy' has no attribute '__version__'

In [1]:
from nba_api.stats.endpoints import LeagueGameLog

logs = LeagueGameLog(season='2024', league_id='10')
df = logs.get_data_frames()[0]

print(df.shape)
print(df.columns.tolist())

(480, 29)
['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'PLUS_MINUS', 'VIDEO_AVAILABLE']

In [2]:
df.head(10)

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22024,1611661313,NYL,New York Liberty,1022400001,2024-05-14,NYL @ WAS,W,200,32,...,28,36,21,8,5,20,20,85,5,1
1,22024,1611661317,PHO,Phoenix Mercury,1022400003,2024-05-14,PHO @ LVA,L,200,29,...,27,37,21,6,6,17,23,80,-9,1
2,22024,1611661319,LVA,Las Vegas Aces,1022400003,2024-05-14,LVA vs. PHO,W,200,29,...,29,37,17,7,5,11,12,89,9,1
3,22024,1611661322,WAS,Washington Mystics,1022400001,2024-05-14,WAS vs. NYL,L,200,31,...,24,34,22,9,7,14,20,80,-5,1
4,22024,1611661323,CON,Connecticut Sun,1022400002,2024-05-14,CON vs. IND,W,200,32,...,22,30,20,11,1,15,22,92,21,1
5,22024,1611661324,MIN,Minnesota Lynx,1022400004,2024-05-14,MIN @ SEA,W,200,34,...,32,39,23,15,8,17,15,83,13,1
6,22024,1611661325,IND,Indiana Fever,1022400002,2024-05-14,IND @ CON,L,200,24,...,24,28,16,6,5,25,21,71,-21,1
7,22024,1611661328,SEA,Seattle Storm,1022400004,2024-05-14,SEA vs. MIN,L,200,29,...,29,43,14,10,5,17,12,70,-13,1
8,22024,1611661320,LAS,Los Angeles Sparks,1022400006,2024-05-15,LAS vs. ATL,L,200,28,...,27,35,24,8,2,14,17,81,-11,1
9,22024,1611661321,DAL,Dallas Wings,1022400005,2024-05-15,DAL vs. CHI,W,200,37,...,27,42,18,7,12,15,20,87,8,1

In [3]:
logs = LeagueGameLog(season='2024', league_id='10', player_or_team_abbreviation='P')
df = logs.get_data_frames()[0]

print(df.shape)
df.head(10)

(4515, 32)

,SEASON_ID,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,...,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,FANTASY_PTS,VIDEO_AVAILABLE
0,22024,1631055,Nyara Sabally,1611661313,NYL,New York Liberty,1022400001,2024-05-14,NYL @ WAS,W,...,0,0,1,1,0,1,2,2,8.0,1
1,22024,1629482,Sophie Cunningham,1611661317,PHO,Phoenix Mercury,1022400003,2024-05-14,PHO @ LVA,L,...,4,1,0,1,1,4,6,-4,14.3,1
2,22024,1630134,Sug Sutton,1611661317,PHO,Phoenix Mercury,1022400003,2024-05-14,PHO @ LVA,L,...,1,2,2,0,3,2,2,-20,9.2,1
3,22024,1629498,Jackie Young,1611661319,LVA,Las Vegas Aces,1022400003,2024-05-14,LVA vs. PHO,W,...,7,6,3,2,1,1,23,12,54.4,1
4,22024,1628279,Brittney Sykes,1611661322,WAS,Washington Mystics,1022400001,2024-05-14,WAS vs. NYL,L,...,10,7,2,0,2,3,14,1,40.5,1
5,22024,1628878,Ariel Atkins,1611661322,WAS,Washington Mystics,1022400001,2024-05-14,WAS vs. NYL,L,...,2,3,3,1,1,1,20,7,37.9,1
6,22024,1627676,Tiffany Mitchell,1611661323,CON,Connecticut Sun,1022400002,2024-05-14,CON vs. IND,W,...,1,1,0,0,0,2,4,9,6.7,1
7,22024,1629524,Bridget Carleton,1611661324,MIN,Minnesota Lynx,1022400004,2024-05-14,MIN @ SEA,W,...,2,3,3,1,0,0,5,16,23.9,1
8,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400002,2024-05-14,IND @ CON,L,...,0,3,2,0,10,4,20,-13,20.5,1
9,22024,1628920,Mercedes Russell,1611661328,SEA,Seattle Storm,1022400004,2024-05-14,SEA vs. MIN,L,...,3,0,0,0,1,1,7,-2,9.6,1

In [4]:
df.isnull().sum()

SEASON_ID               0
PLAYER_ID               0
PLAYER_NAME             0
TEAM_ID                 0
TEAM_ABBREVIATION       0
TEAM_NAME               0
GAME_ID                 0
GAME_DATE               0
MATCHUP                 0
WL                      0
MIN                     0
FGM                     0
FGA                     0
FG_PCT                308
FG3M                    0
FG3A                    0
FG3_PCT              1335
FTM                     0
FTA                     0
FT_PCT               2099
OREB                    0
DREB                    0
REB                     0
AST                     0
STL                     0
BLK                     0
TOV                     0
PF                      0
PTS                     0
PLUS_MINUS              0
FANTASY_PTS             0
VIDEO_AVAILABLE         0
dtype: int64

In [5]:
df[df['PLAYER_NAME'] == 'Caitlin Clark']

,SEASON_ID,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,...,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,FANTASY_PTS,VIDEO_AVAILABLE
8,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400002,2024-05-14,IND @ CON,L,...,0,3,2,0,10,4,20,-13,20.5,1
121,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400007,2024-05-16,IND vs. NYL,L,...,7,6,0,1,3,5,9,-24,26.4,1
226,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400010,2024-05-18,IND @ NYL,L,...,6,8,1,0,8,3,22,-9,36.2,1
295,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400015,2024-05-20,IND vs. CON,L,...,3,5,0,2,5,5,17,-18,29.1,1
369,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400020,2024-05-22,IND @ SEA,L,...,7,7,0,2,3,0,21,7,42.9,1
445,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400024,2024-05-24,IND @ LAS,W,...,10,8,4,1,2,2,11,5,48.0,1
536,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400027,2024-05-25,IND @ LVA,L,...,5,7,1,0,6,2,8,-18,21.5,1
615,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400033,2024-05-28,IND vs. LAS,L,...,5,6,3,3,7,5,30,4,56.0,1
733,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400038,2024-05-30,IND vs. SEA,L,...,3,9,0,1,7,2,20,-13,33.1,1
833,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400044,2024-06-01,IND vs. CHI,W,...,8,6,1,0,5,2,11,2,27.6,1
901,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400046,2024-06-02,IND @ NYL,L,...,2,5,2,1,3,2,3,-28,18.9,1
1105,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400056,2024-06-07,IND @ WAS,W,...,8,6,4,0,8,3,30,5,52.6,1
1268,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400066,2024-06-10,IND @ CON,L,...,0,2,1,0,3,4,10,-30,13.0,1
1359,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400071,2024-06-13,IND vs. ATL,W,...,4,6,0,2,7,1,7,2,19.8,1
1532,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400079,2024-06-16,IND vs. CHI,W,...,8,9,0,2,5,3,23,10,47.1,1
1608,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400084,2024-06-19,IND vs. WAS,W,...,12,6,4,0,6,2,18,12,47.4,1
1704,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400089,2024-06-21,IND @ ATL,W,...,4,7,0,1,7,4,16,13,27.3,1
1788,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400096,2024-06-23,IND @ CHI,L,...,6,13,4,0,5,4,17,-1,50.7,1
1880,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400101,2024-06-27,IND @ SEA,L,...,6,7,0,1,6,1,15,-7,29.7,1
2052,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400108,2024-06-30,IND @ PHO,W,...,9,12,0,0,6,3,15,3,37.8,1
2124,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400113,2024-07-02,IND @ LVA,L,...,6,11,1,0,6,5,13,-19,33.7,1
2310,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400121,2024-07-06,IND vs. NYL,W,...,12,13,2,0,4,3,19,9,54.9,1
2479,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400129,2024-07-10,IND vs. WAS,L,...,5,13,5,3,5,5,29,-3,73.5,1
2517,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400135,2024-07-12,IND vs. PHO,W,...,6,13,1,2,6,2,20,9,49.7,1
2650,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400142,2024-07-14,IND @ MIN,W,...,3,6,2,0,6,3,17,1,29.6,1
2752,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400148,2024-07-17,IND @ DAL,L,...,6,19,0,0,6,1,24,-8,53.7,1
2880,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400153,2024-08-16,IND vs. PHO,W,...,5,10,0,0,5,2,29,13,45.0,1
2981,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400160,2024-08-18,IND vs. SEA,W,...,5,9,1,2,5,3,23,18,46.5,1
3233,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400173,2024-08-24,IND @ MIN,L,...,5,8,1,0,7,4,23,-13,37.0,1
3297,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400176,2024-08-26,IND @ ATL,W,...,7,7,2,1,2,4,19,3,44.9,1
3421,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400180,2024-08-28,IND vs. CON,W,...,5,5,1,1,7,2,19,3,31.5,1
3482,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400185,2024-08-30,IND @ CHI,W,...,4,12,1,0,3,3,31,23,53.8,1
3623,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400192,2024-09-01,IND @ DAL,W,...,4,12,1,0,7,3,28,7,46.8,1
3716,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400199,2024-09-04,IND vs. LAS,W,...,10,10,3,0,7,1,24,7,53.0,1
3785,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400204,2024-09-06,IND vs. MIN,L,...,8,8,0,1,7,2,25,-7,42.6,1
3959,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400208,2024-09-08,IND vs. ATL,W,...,5,12,0,0,9,3,26,4,41.0,1
4052,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400215,2024-09-11,IND vs. LVA,L,...,3,6,0,0,5,3,16,-8,23.6,1
4143,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400220,2024-09-13,IND vs. LVA,L,...,8,9,1,0,6,4,18,0,38.1,1
4230,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400224,2024-09-15,IND vs. DAL,W,...,2,8,3,0,5,1,35,1,53.4,1
4429,22024,1642286,Caitlin Clark,1611661325,IND,Indiana Fever,1022400237,2024-09-19,IND @ WAS,L,...,5,8,1,0,3,0,8,1,26.0,1

In [6]:
df['PTS'].describe()

count    4515.000000
mean        8.682171
std         7.657212
min         0.000000
25%         2.000000
50%         7.000000
75%        13.000000
max        42.000000
Name: PTS, dtype: float64

In [7]:
df.to_csv('../data/wnba_2024_game_logs.csv', index=False)
print("Saved!")

Saved!

In [8]:
# Fill missing percentages with 0 (player had 0 attempts, so 0% makes sense)
df['FG_PCT'] = df['FG_PCT'].fillna(0)
df['FG3_PCT'] = df['FG3_PCT'].fillna(0)
df['FT_PCT'] = df['FT_PCT'].fillna(0)

# Convert GAME_DATE to an actual date type so we can sort by it
df['GAME_DATE'] = pd.to_datetime(df['GAME_DATE'])

# Add a home/away column — if MATCHUP contains '@', player is away
df['IS_HOME'] = df['MATCHUP'].apply(lambda x: 0 if '@' in x else 1)

print(df[['PLAYER_NAME', 'GAME_DATE', 'MATCHUP', 'IS_HOME', 'PTS']].head(10))

NameError: name 'pd' is not defined

In [9]:
import pandas as pd

# Fill missing percentages with 0 (player had 0 attempts, so 0% makes sense)
df['FG_PCT'] = df['FG_PCT'].fillna(0)
df['FG3_PCT'] = df['FG3_PCT'].fillna(0)
df['FT_PCT'] = df['FT_PCT'].fillna(0)

# Convert GAME_DATE to an actual date type so we can sort by it
df['GAME_DATE'] = pd.to_datetime(df['GAME_DATE'])

# Add a home/away column — if MATCHUP contains '@', player is away
df['IS_HOME'] = df['MATCHUP'].apply(lambda x: 0 if '@' in x else 1)

print(df[['PLAYER_NAME', 'GAME_DATE', 'MATCHUP', 'IS_HOME', 'PTS']].head(10))

         PLAYER_NAME  GAME_DATE      MATCHUP  IS_HOME  PTS
0      Nyara Sabally 2024-05-14    NYL @ WAS        0    2
1  Sophie Cunningham 2024-05-14    PHO @ LVA        0    6
2         Sug Sutton 2024-05-14    PHO @ LVA        0    2
3       Jackie Young 2024-05-14  LVA vs. PHO        1   23
4     Brittney Sykes 2024-05-14  WAS vs. NYL        1   14
5       Ariel Atkins 2024-05-14  WAS vs. NYL        1   20
6   Tiffany Mitchell 2024-05-14  CON vs. IND        1    4
7   Bridget Carleton 2024-05-14    MIN @ SEA        0    5
8      Caitlin Clark 2024-05-14    IND @ CON        0   20
9   Mercedes Russell 2024-05-14  SEA vs. MIN        1    7

In [10]:
# Sort so each player's games are in date order
df = df.sort_values(['PLAYER_NAME', 'GAME_DATE'])

# For each player, calculate their rolling 5-game average points
# min_periods=1 means it still calculates even if a player has fewer than 5 games so far
df['PTS_ROLLING_AVG_5'] = (
    df.groupby('PLAYER_NAME')['PTS']
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

print(df[['PLAYER_NAME', 'GAME_DATE', 'PTS', 'PTS_ROLLING_AVG_5']].head(20))

      PLAYER_NAME  GAME_DATE  PTS  PTS_ROLLING_AVG_5
58    A'ja Wilson 2024-05-14   30                NaN
202   A'ja Wilson 2024-05-18   22          30.000000
324   A'ja Wilson 2024-05-21   21          26.000000
510   A'ja Wilson 2024-05-25   29          24.333333
658   A'ja Wilson 2024-05-29   29          25.500000
788   A'ja Wilson 2024-05-31   28          26.200000
987   A'ja Wilson 2024-06-05   36          25.800000
1123  A'ja Wilson 2024-06-07   29          28.600000
1203  A'ja Wilson 2024-06-09   31          30.200000
1321  A'ja Wilson 2024-06-11   28          30.600000
1367  A'ja Wilson 2024-06-13   32          30.400000
1462  A'ja Wilson 2024-06-15   21          31.200000
1624  A'ja Wilson 2024-06-19   27          28.200000
1697  A'ja Wilson 2024-06-21   26          27.800000
1900  A'ja Wilson 2024-06-27   31          26.800000
1969  A'ja Wilson 2024-06-29   11          27.400000
2114  A'ja Wilson 2024-07-02   28          23.200000
2186  A'ja Wilson 2024-07-04   18          24.600000
2252  A'ja Wilson 2024-07-05   35          22.800000
2326  A'ja Wilson 2024-07-07   28          24.600000

In [11]:
logs_2025 = LeagueGameLog(season='2025', league_id='10', player_or_team_abbreviation='P')
df_2025 = logs_2025.get_data_frames()[0]
print(df_2025.shape)
print(df_2025['GAME_DATE'].min(), df_2025['GAME_DATE'].max())

ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

In [12]:
logs_2025 = LeagueGameLog(season='2025', league_id='10', player_or_team_abbreviation='P', timeout=60)
df_2025 = logs_2025.get_data_frames()[0]
print(df_2025.shape)

(5407, 32)

In [13]:
# Stack both seasons on top of each other
df_all = pd.concat([df, df_2025], ignore_index=True)

print(df_all.shape)
print(df_all['GAME_DATE'].min(), '→', df_all['GAME_DATE'].max())

(9922, 34)

TypeError: '<=' not supported between instances of 'Timestamp' and 'str'

In [14]:
df_all = pd.concat([df, df_2025], ignore_index=True)

# Convert GAME_DATE for the whole combined dataset
df_all['GAME_DATE'] = pd.to_datetime(df_all['GAME_DATE'])

print(df_all.shape)
print(df_all['GAME_DATE'].min(), '→', df_all['GAME_DATE'].max())

(9922, 34)
2024-05-14 00:00:00 → 2025-09-11 00:00:00

In [15]:
logs_2026 = LeagueGameLog(season='2026', league_id='10', player_or_team_abbreviation='P', timeout=60)
df_2026 = logs_2026.get_data_frames()[0]
print(df_2026.shape)

(853, 32)

In [16]:
df_all.to_csv('../data/wnba_all_seasons.csv', index=False)
print("Saved!", df_all.shape)

Saved! (9922, 34)

In [17]:
# Fill missing percentages
df_all['FG_PCT'] = df_all['FG_PCT'].fillna(0)
df_all['FG3_PCT'] = df_all['FG3_PCT'].fillna(0)
df_all['FT_PCT'] = df_all['FT_PCT'].fillna(0)

# Home/away indicator
df_all['IS_HOME'] = df_all['MATCHUP'].apply(lambda x: 0 if '@' in x else 1)

# Sort by player and date, then calculate rolling average
df_all = df_all.sort_values(['PLAYER_NAME', 'GAME_DATE'])
df_all['PTS_ROLLING_AVG_5'] = (
    df_all.groupby('PLAYER_NAME')['PTS']
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

print(df_all[['PLAYER_NAME', 'GAME_DATE', 'IS_HOME', 'PTS', 'PTS_ROLLING_AVG_5']].head(10))

   PLAYER_NAME  GAME_DATE  IS_HOME  PTS  PTS_ROLLING_AVG_5
0  A'ja Wilson 2024-05-14        1   30                NaN
1  A'ja Wilson 2024-05-18        1   22          30.000000
2  A'ja Wilson 2024-05-21        1   21          26.000000
3  A'ja Wilson 2024-05-25        1   29          24.333333
4  A'ja Wilson 2024-05-29        0   29          25.500000
5  A'ja Wilson 2024-05-31        0   28          26.200000
6  A'ja Wilson 2024-06-05        0   36          25.800000
7  A'ja Wilson 2024-06-07        1   29          28.600000
8  A'ja Wilson 2024-06-09        0   31          30.200000
9  A'ja Wilson 2024-06-11        1   28          30.600000

In [18]:
# The threshold — we're asking "did the player score more than 15.5 points?"
THRESHOLD = 15.5

df_all['HIT_OVER'] = (df_all['PTS'] > THRESHOLD).astype(int)

# Check the split — how often does the over hit?
print(df_all['HIT_OVER'].value_counts())
print(f"\nOver hits {df_all['HIT_OVER'].mean():.1%} of the time")

HIT_OVER
0    8131
1    1791
Name: count, dtype: int64

Over hits 18.1% of the time

In [19]:
# Target: did the player score more than their own rolling average?
df_all['HIT_OVER'] = (df_all['PTS'] > df_all['PTS_ROLLING_AVG_5']).astype(int)

print(df_all['HIT_OVER'].value_counts())
print(f"\nOver hits {df_all['HIT_OVER'].mean():.1%} of the time")

HIT_OVER
0    5639
1    4283
Name: count, dtype: int64

Over hits 43.2% of the time

In [20]:
# Select the features (inputs) and target (output)
features = ['PTS_ROLLING_AVG_5', 'IS_HOME', 'MIN', 'FGA', 'FG_PCT', 'FG3A', 'FT_PCT']
target = 'HIT_OVER'

# Drop rows where rolling average is NaN (first game of each player's career)
model_df = df_all[features + [target]].dropna()

print(model_df.shape)
print(model_df.head())

(9703, 8)
   PTS_ROLLING_AVG_5  IS_HOME  MIN  FGA  FG_PCT  FG3A  FT_PCT  HIT_OVER
1          30.000000        1   32   20   0.450     2   0.750         0
2          26.000000        1   32   18   0.444     0   0.625         0
3          24.333333        1   31   18   0.667     2   1.000         1
4          25.500000        0   32   23   0.478     1   0.700         1
5          26.200000        0   35   27   0.444     1   1.000         1

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

X = model_df[features]
y = model_df[target]

# 80% for training, 20% for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)

predictions = model.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, predictions):.1%}")

ModuleNotFoundError: No module named 'sklearn'

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

X = model_df[features]
y = model_df[target]

# 80% for training, 20% for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)

predictions = model.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, predictions):.1%}")

Accuracy: 87.8%

In [23]:
features = ['PTS_ROLLING_AVG_5', 'IS_HOME']

X = model_df[features]
y = model_df[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)

predictions = model.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, predictions):.1%}")

Accuracy: 55.7%

In [24]:
# Add rolling averages for minutes and field goal attempts (pre-game features)
df_all['MIN_ROLLING_AVG_5'] = (
    df_all.groupby('PLAYER_NAME')['MIN']
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

df_all['FGA_ROLLING_AVG_5'] = (
    df_all.groupby('PLAYER_NAME')['FGA']
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

features = ['PTS_ROLLING_AVG_5', 'MIN_ROLLING_AVG_5', 'FGA_ROLLING_AVG_5', 'IS_HOME']

model_df = df_all[features + [target]].dropna()
X = model_df[features]
y = model_df[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression()
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, predictions):.1%}")

Accuracy: 57.6%

In [25]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(n_estimators=100, random_state=42)
model_rf.fit(X_train, y_train)

predictions_rf = model_rf.predict(X_test)
print(f"Logistic Regression: {accuracy_score(y_test, predictions):.1%}")
print(f"Random Forest:       {accuracy_score(y_test, predictions_rf):.1%}")

Logistic Regression: 57.6%
Random Forest:       53.8%

In [26]:
mport pandas as pd

# See which features matter most to the Random Forest
importances = pd.Series(model_rf.feature_importances_, index=features)
print(importances.sort_values(ascending=False))

SyntaxError: invalid syntax (405946686.py, line 1)

In [27]:
import pandas as pd

# See which features matter most to the Random Forest
importances = pd.Series(model_rf.feature_importances_, index=features)
print(importances.sort_values(ascending=False))

MIN_ROLLING_AVG_5    0.394414
PTS_ROLLING_AVG_5    0.287855
FGA_ROLLING_AVG_5    0.272935
IS_HOME              0.044796
dtype: float64

In [28]:
# 10-game rolling average (longer trend)
df_all['PTS_ROLLING_AVG_10'] = (
    df_all.groupby('PLAYER_NAME')['PTS']
    .transform(lambda x: x.shift(1).rolling(10, min_periods=1).mean())
)

# Rolling assists and rebounds — overall form indicator
df_all['AST_ROLLING_AVG_5'] = (
    df_all.groupby('PLAYER_NAME')['AST']
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

df_all['REB_ROLLING_AVG_5'] = (
    df_all.groupby('PLAYER_NAME')['REB']
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

features = ['PTS_ROLLING_AVG_5', 'PTS_ROLLING_AVG_10', 'MIN_ROLLING_AVG_5', 
            'FGA_ROLLING_AVG_5', 'AST_ROLLING_AVG_5', 'REB_ROLLING_AVG_5', 'IS_HOME']

model_df = df_all[features + [target]].dropna()
X = model_df[features]
y = model_df[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model_rf = RandomForestClassifier(n_estimators=100, random_state=42)
model_rf.fit(X_train, y_train)
predictions_rf = model_rf.predict(X_test)
print(f"Random Forest: {accuracy_score(y_test, predictions_rf):.1%}")

Random Forest: 55.4%

In [29]:
import pickle

# Go back to the best model setup
features = ['PTS_ROLLING_AVG_5', 'MIN_ROLLING_AVG_5', 'FGA_ROLLING_AVG_5', 'IS_HOME']
model_df = df_all[features + [target]].dropna()
X = model_df[features]
y = model_df[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
from sklearn.linear_model import LogisticRegression
best_model = LogisticRegression()
best_model.fit(X_train, y_train)

# Save the model to disk
with open('../models/wnba_model.pkl', 'wb') as f:
    pickle.dump(best_model, f)

print("Model saved!")

FileNotFoundError: [Errno 2] No such file or directory: '../models/wnba_model.pkl'

In [30]:
import pickle

# Go back to the best model setup
features = ['PTS_ROLLING_AVG_5', 'MIN_ROLLING_AVG_5', 'FGA_ROLLING_AVG_5', 'IS_HOME']
model_df = df_all[features + [target]].dropna()
X = model_df[features]
y = model_df[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
from sklearn.linear_model import LogisticRegression
best_model = LogisticRegression()
best_model.fit(X_train, y_train)

# Save the model to disk
with open('../models/wnba_model.pkl', 'wb') as f:
    pickle.dump(best_model, f)

print("Model saved!")

Model saved!